name: trufflehog

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 6"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    uses: cboone/gh-actions/.github/workflows/scan-for-secrets.yml@844bf31d4ec26df9d0aa531e79d8c3fccf9f0638 # v3.1.0
    with:
      tool: trufflehog
